#ifndef COMMONDEFINES_H_INCLUDED
#define COMMONDEFINES_H_INCLUDED

#define BOX_VERTICES_FTL	0
#define BOX_VERTICES_FTR	1
#define BOX_VERTICES_FBL	2
#define BOX_VERTICES_FBR 	3
#define BOX_VERTICES_BTL 	4
#define BOX_VERTICES_BTR	5
#define BOX_VERTICES_BBL	6
#define BOX_VERTICES_BBR	7

#define AABB_EXTENTS_MIN	0
#define AABB_EXTENTS_MAX	1

#endif // COMMONDEFINES_H_INCLUDED
